FROM python:3.8.9-alpine as back-stage
WORKDIR /app
ENV FLASK_APP=app.py
RUN  apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev \
    && apk add --update --no-cache libxslt-dev
COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip && python -m pip install -r requirements.txt
COPY . .
COPY root.crt /root/.postgresql/root.crt
CMD ["python3", "-m", "flask", "run", "-h $(hostname -i)"]

